config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "admin/dashboard#index"
  namespace :admin do
    # Defines the root path route ("/")
    resources :products
    resources :sales, only: [:new, :create, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id              :integer          not null, primary key
#  description     :string
#  low_stock_level :integer          default(0), not null
#  name            :string
#  price           :string
#  quantity        :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class Product < ApplicationRecord
  has_one_attached :image
  has_many :sales, dependent: :destroy

  validates :low_stock_level, numericality: { greater_than_or_equal_to: 0 }
  validates :name, :quantity, :price, :description, presence: true

  scope :search_with, lambda { |q|
    where('name ILIKE ?', "%#{q}%")
  }
end

app/models/sale.rb
# == Schema Information
#
# Table name: sales
#
#  id          :integer          not null, primary key
#  quantity    :integer
#  total_price :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  product_id  :integer          not null
#
# Indexes
#
#  index_sales_on_product_id  (product_id)
#
# Foreign Keys
#
#  product_id  (product_id => products.id)
#
class Sale < ApplicationRecord
  belongs_to :product

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :quantity_greater_than_product_quantity_in_stock

  before_create :calculate_total_price
  after_create :reduce_product_quantity

  def date
    created_at.strftime("%a %d-%m-%Y at %I:%M%p")
  end

  def product_name
    product.name
  end

  private

  def calculate_total_price
    return unless product && quantity

    total_price = product.price.to_f * quantity
  end

  def reduce_product_quantity
    product.quantity -= quantity
    product.save
  end

  def quantity_greater_than_product_quantity_in_stock
    if quantity > product.quantity
      errors.add(:quantity, "Sale quantity: #{quantity} exceeds product quantity in stock: #{product.quantity} !")
    end
  end
end

app/controllers/admin/dashboard_controller.rb
module Admin
  class DashboardController < ApplicationController
    def index
      @products = Product.all
      @sales = Sale.all
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  # before_action :set_filter, only: [:index]

  def index
    # @products = @filter.scope
    @products = Product.all
    respond_to do |format|
      format.html
      format.csv do
        filename = ['Products', Time.now].join(' ')
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = "attachment; filename=#{filename}.csv"
        render template: 'admin/products/index'
      end
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to admin_product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :quantity, :low_stock_level, :description, :image)
  end

  def set_filter
    @filter = ::ProductFilter.new
    @filter.update(filter_params)
  end

  def filter_params
    params.permit(:product_name)
  end
end

app/controllers/admin/sales_controller.rb
class Admin::SalesController < ApplicationController

  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.new(sale_params)
    respond_to do |format|
      if @sale.save

        if @sale.product.quantity <= @sale.product.low_stock_level
          LowStockMailer.low_stock_notification(@sale).deliver_now
        end

        format.html { redirect_to  admin_sales_path, notice: "Sale made successfully !" }
      else
        @sale_errors = @sale.errors
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update("error_explanation",
              partial: "shared/errors",
              locals: { errors: [] << @sale.errors }
            ),
            turbo_stream.update(@sale,
              partial: "form",
              locals: { sale: @sale }
            )
          ]
        end
      end
    end
  end

  def index
    @sales = Sale.all
  end

  private

  def sale_params
    params.require(:sale).permit(:product_id, :quantity)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  require 'csv'
  allow_browser versions: :modern
end

app/helpers/admin/sales_helper.rb
module Admin::SalesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def slide_over_form_wrapper(title:, subtitle: nil, &block)
    content = capture &block

    render partial: 'shared/slide_over', locals: { title:, subtitle:, content: }
  end

  def error_messages(errors = nil)
    render "shared/errors",
     errors: [] << errors
  end
end

app/views/admin/dashboard/index.html.erb
<div class='grid grid-cols-12 gap-x-4 mb-4 p-8'>
  <div class='col-span-6 mb-5 rounded-lg bg-white'>
    <a href="#" class="p-[30px] inline-block">
      <div class="cashier-quickview-box">
        <div class="cashier-quickview-box-icon mb-5 flex">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 inline me-4">
            <path stroke-linecap="round" stroke-linejoin="round" d="m21 7.5-2.25-1.313M21 7.5v2.25m0-2.25-2.25 1.313M3 7.5l2.25-1.313M3 7.5l2.25 1.313M3 7.5v2.25m9 3 2.25-1.313M12 12.75l-2.25-1.313M12 12.75V15m0 6.75 2.25-1.313M12 21.75V19.5m0 2.25-2.25-1.313m0-16.875L12 2.25l2.25 1.313M21 14.25v2.25l-2.25 1.313m-13.5 0L3 16.5v-2.25" />
          </svg>
          <h4 class="text-[22px] font-extrabold text-heading"><%= @products.size %> Products </h4>
        </div>
      </div>
    </a>
  </div>
  <div class='col-span-6 mb-5 rounded-lg bg-white'>
    <a href="#" class="p-[30px] inline-block">
      <div class="cashier-quickview-box">
        <div class="cashier-quickview-box-icon mb-5 flex">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 inline me-4">
            <path stroke-linecap="round" stroke-linejoin="round" d="m21 7.5-2.25-1.313M21 7.5v2.25m0-2.25-2.25 1.313M3 7.5l2.25-1.313M3 7.5l2.25 1.313M3 7.5v2.25m9 3 2.25-1.313M12 12.75l-2.25-1.313M12 12.75V15m0 6.75 2.25-1.313M12 21.75V19.5m0 2.25-2.25-1.313m0-16.875L12 2.25l2.25 1.313M21 14.25v2.25l-2.25 1.313m-13.5 0L3 16.5v-2.25" />
          </svg>
          <h4 class="text-[22px] font-extrabold text-heading"><%= @sales.size %> Sales </h4>
        </div>
      </div>
    </a>
  </div>
</div>

app/views/admin/products/_filter.html.erb
<div class="rounded-md">
  <%= form_with(url: admin_products_path, method: :get, data: { turbo_frame: "products-table"}) do |form| %>
    <div class=''>
      <%= form.search_field :product_name, placeholder: "Search by name", oninput: "this.form.requestSubmit()", class: "appearance-none block w-full rounded-md border-2 bg-white p-2 text-gray-900 shadow-sm border-2 border-purple-700 placeholder:text-gray-400 text-sm leading-6" %>
    </div>
  <% end %>
</div>

app/views/admin/products/_form.html.erb
<%= form_with model: @product, url: @product.new_record? ? admin_products_path : admin_product_path(@product), method: @product.new_record? ? :post : :patch, data: { turbo_stream: true, turbo_frame: "_top" }, class: "w-full h-full p-6 flex flex-col justify-between" do |form| %>
  <div>
    <div class="flex flex-wrap -mx-3 mb-6 space-y-4">
      <div class="w-full px-3">
        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
          Product Name
        </label>
        <%= form.text_field :name, class: "appearance-none block w-full bg-gray-200 text-gray-700 rounded py-3 px-4 mb-3 leading-tight focus:border-purple-600 focus:bg-white", required: true, placeholder:"Blueband Choco" %>
      </div>
      <div class="w-full px-3">
        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-last-name">
          Price
        </label>
        <%= form.text_field :price, class: "appearance-none block w-full bg-gray-200 text-gray-700 rounded py-3 px-4 mb-3 leading-tight focus:border-purple-600 focus:bg-white", required: true, placeholder:"Blueband Choco" %>
      </div>
    </div>
    <div class="flex flex-wrap -mx-3 space-y-4">
      <div class="w-full px-3">
        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-password">
          Quantity
        </label>
        <%= form.text_field :quantity, class: "appearance-none block w-full bg-gray-200 text-gray-700 rounded py-3 px-4 mb-3 leading-tight focus:border-purple-600 focus:bg-white", required: true, placeholder:"Blueband Choco" %>
      </div>
      <div class="w-full px-3">
        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-password">
          Low Stock Level
        </label>
        <%= form.text_field :low_stock_level, class: "appearance-none block w-full bg-gray-200 text-gray-700 rounded py-3 px-4 mb-2 leading-tight focus:border-purple-600 focus:bg-white", required: true, placeholder:"Restock level" %>
      </div>
      <div class="w-full px-3">
        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-password">
          Description
        </label>
        <%= form.text_area :description, class: "appearance-none block w-full bg-gray-200 text-gray-700 rounded py-3 px-4 mb-2 leading-tight focus:border-purple-600 focus:bg-white", required: true, placeholder:"Product description", rows: "6" %>
        <p class="text-gray-600 text-xs italic">Make it as long and descriptive as possible.</p>
      </div>
      <div class="w-full px-3">
        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-password">
          Attach Image
        </label>
        <%= form.file_field :image, class: "appearance-none block w-full bg-gray-200 text-gray-700 rounded py-3 px-4 mb-2 leading-tight focus:border-purple-600 focus:bg-white", required: true, placeholder:"Product image" %>
        <p class="text-gray-600 text-xs italic">Choose an appropriate image from your local library.</p>
      </div>
    </div>
  </div>
  <div>
   <%= form.submit class: "w-full py-2 px-3 space-x-2 text-white font-semibold bg-purple-900 flex items-center rounded-lg hover:cursor-pointer" %>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<%= turbo_frame_tag product do %>
  <tr>
    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= product.name %></td>
    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= product.price %></td>
    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= product.quantity %></td>
    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= product.low_stock_level %></td>
    <td class="whitespace-nowrap text-wrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= product.description %></td>
    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6 flex space-x-2">
      <%= link_to admin_product_path(product), data: { turbo_frame: "_top" } do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-4 h-4">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
        </svg>
      <% end %>
      <%= link_to edit_admin_product_path(product), data: { turbo_frame: "slide-over"} do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-4 h-4">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
        </svg>
      <% end %>
      <%= link_to admin_product_path(product), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this product?" } do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-4 h-4">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
        </svg>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/admin/products/edit.html.erb
<%= turbo_frame_tag @product do %>
  <%= slide_over_form_wrapper(title: 'Update Product', subtitle: 'Edit Product Details') do %>
    <%= render 'form', product: @product %>
  <% end %>
<% end %>

app/views/admin/products/index.csv.erb
<%- headers = ['Product Name', 'Price', 'Quantity In Stock', 'Low Stock Level'] -%>
<%= CSV.generate_line headers %>
<%- @products.each do |product| -%>
<%= CSV.generate_line([product.name, product.price, product.quantity, product.low_stock_level]).html_safe -%>
<%- end -%>

app/views/admin/products/index.html.erb
<div class="h-full w-full py-8 px-3 md:px-8 mb-seller-dashboard-cards">
  <!-- heading section -->
  <div class='flex flex-1 justify-between'>
    <!-- page heading -->
    <div class='text-xl font-semibold'>
      <h3>Products</h3>
    </div>
    <!-- slide over -->
    <div>
      <%= link_to new_admin_product_path, data: { turbo_frame: "slide-over, #{dom_id(Product.new)}" }, class: "py-2 px-3 space-x-2 text-white font-semibold bg-purple-700 flex items-center rounded-lg" do %>
        <span>Create Product</span>
      <% end %>
    </div>
  </div>
  <div class='flex justify-end mt-10 mb-2'>
    <!-- export -->
    <%= link_to 'Export CSV', admin_products_path(format: :csv),  data: {turbo_frame: "_top"}, class: "block rounded-md bg-gray-300 px-3 py-2 text-center text-sm font-semibold text-dark shadow-sm bg-white border-2 border-purple-700" %>
  </div>
  <!-- table section -->
  <% unless @products.blank? %>
    <%= turbo_frame_tag "products-table" do %>
      <div class='mb-8 w-full'>
        <div class='flex flex-col space-y-2 md:space-y-4'>
          <div class='w-full overflow-hidden'>
            <div class='w-full overflow-x-auto scrollbar-hide border border-gray-400 rounded-lg'>
              <table class="w-full divide-y divide-gray-300">
                <thead class="bg-purple-800 h-auto">
                  <tr class='text-nowrap'>
                    <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-base font-semibold text-white sm:pl-6">Product Name</th>
                    <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-base font-semibold text-white sm:pl-6">Price</th>
                    <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-base font-semibold text-white sm:pl-6">Quantity In Stock</th>
                    <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-base font-semibold text-white sm:pl-6">Low Stock Level</th>
                    <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-base font-semibold text-white sm:pl-6">Description</th>
                    <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-base font-semibold text-white sm:pl-6">Actions</th>
                  </tr>
                </thead>
                <%= turbo_frame_tag "products" do %>
                  <tbody class="divide-y divide-gray-300 bg-white">
                    <%= render @products %>
                  </tbody>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      </div>
    <% end%>
  <% else %>
    <div class="max-w-lg mx-auto mt-8">
      <%= link_to new_admin_product_path, data: { turbo_frame: "slide-over, #{dom_id(Product.new)}" }, class: "relative block w-full border-2 border-gray-300 border-dashed rounded-lg p-12 text-center hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500" do %>
        <svg class="mx-auto h-12 w-12 text-gray-400" xmlns="http://www.w3.org/2000/svg" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 14v20c0 4.418 7.163 8 16 8 1.381 0 2.721-.087 4-.252M8 14c0 4.418 7.163 8 16 8s16-3.582 16-8M8 14c0-4.418 7.163-8 16-8s16 3.582 16 8m0 0v14m0-4c0 4.418-7.163 8-16 8S8 28.418 8 24m32 10v6m0 0v6m0-6h6m-6 0h-6" />
        </svg>
        <span class="mt-2 block text-sm font-medium text-gray-900">Create New Product</span>
      <% end %>
    </div>
  <% end %>
</div>

app/views/admin/products/new.html.erb
<%= turbo_frame_tag @product do %>
  <%= slide_over_form_wrapper(title: 'New Product', subtitle: 'Create A New Product') do %>
    <%= render 'form', product: @product %>
  <% end %>
<% end %>

app/views/admin/products/show.html.erb
<% if @product.quantity <= @product.low_stock_level %>
<div class="bg-red-200 border-t-4 border-red-700 rounded-b text-teal-900 px-4 py-3 shadow-md mb-4" role="alert">
  <div class="flex">
    <div class="py-1"><svg class="fill-current h-6 w-6 text-purple-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/></svg></div>
    <div>
      <p class="font-bold text-purple-900">This Product is below the Low Stock Level. Please Restock !</p>
    </div>
  </div>
</div>
<% end %>
<div class="p-6 bg-white rounded-lg w-full h-auto">
  <div class='grid grid-cols-12 gap-x-4'>
    <div class='col-span-3'>
      <div class='w-[200px] h-[200px]'>
        <% if @product.image.attached? %>
          <%= image_tag @product.image, class: "w-full h-full" %>
        <% end %>
      </div>
    </div>
    <div class='col-span-3 space-y-6'>
      <div>
        <p class='text-base font-semibold'>Product Name</p>
        <p><%= @product.name %></p>
      </div>
      <div>
        <p class='text-base font-semibold'>Unit Price</p>
        <p><%= @product.price %></p>
      </div>
    </div>
    <div class='col-span-3 space-y-6'>
      <div>
        <p class='text-base font-semibold'>Quantity In Stock</p>
        <p><%= @product.quantity %></p>
      </div>
      <div>
        <p class='text-base font-semibold'>Low Stock Level</p>
        <p><%= @product.low_stock_level %></p>
      </div>
    </div>
    <div class='col-span-3'>
      <div>
        <p class='text-base font-semibold'>Quantity In Stock</p>
        <p><%= @product.description %></p>
      </div>
    </div>
  </div>
</div>

app/views/admin/sales/_form.html.erb
<%= form_with model: @sale, url: admin_sales_path, data: { turbo_stream: true, turbo_frame: "_top" }, class: "w-full h-full p-6 flex flex-col justify-between" do |form| %>
  <div>
    <div id="error_explanation">
      <%= error_messages(@sale_errors) %>
    </div>
    <div class="flex flex-wrap -mx-3 mb-6 space-y-4">
      <div class="w-full px-3">
        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
          Product
        </label>
        <%= form.select :product_id, Product.all.map { |product| [product.name, product.id] }, { prompt: "Choose a product" }, class: "appearance-none block w-full bg-gray-200 text-gray-700 rounded py-3 px-4 mb-3 leading-tight focus:border-purple-600 focus:bg-white", id: "sale_product_id" %>
      </div>
      <div class="w-full px-3">
        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-password">
          Quantity
        </label>
        <%= form.number_field :quantity, class: "appearance-none block w-full bg-gray-200 text-gray-700 rounded py-3 px-4 mb-3 leading-tight focus:border-purple-600 focus:bg-white", required: true, placeholder:"" %>
      </div>
    </div>
  </div>
  <div>
   <%= form.submit class: "w-full py-2 px-3 space-x-2 text-white font-semibold bg-purple-900 flex items-center rounded-lg hover:cursor-pointer" %>
  </div>
<% end %>

app/views/admin/sales/_sale.html.erb
<%= turbo_frame_tag sale do %>
  <tr>
    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= sale.product_name %></td>
    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= sale.quantity %></td>
    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= sale.total_price %></td>
    <td class="whitespace-nowrap text-wrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6"><%= sale.date %></td>
  </tr>
<% end %>

app/views/admin/sales/index.html.erb
<div class="h-full w-full py-8 px-3 md:px-8 mb-seller-dashboard-cards">
  <!-- heading section -->
  <div class='flex flex-1 justify-between'>
    <!-- page heading -->
    <div class='text-xl font-semibold'>
      <h3>Sales</h3>
    </div>
    <!-- slide over -->
    <div>
      <%= link_to new_admin_sale_path, data: { turbo_frame: "slide-over, #{dom_id(Sale.new)}" }, class: "py-2 px-3 space-x-2 text-white font-semibold bg-purple-900 flex items-center rounded-lg" do %>
        <span>Create Sale</span>
      <% end %>
    </div>
  </div>
  <!-- table section -->
  <% unless @sales.blank? %>
    <%= turbo_frame_tag "sales-table" do %>
      <div class='my-8 w-full'>
        <div class='flex flex-col space-y-2 md:space-y-4'>
          <div class='w-full overflow-hidden'>
            <div class='w-full overflow-x-auto scrollbar-hide border border-gray-400 rounded-lg'>
              <table class="w-full divide-y divide-gray-300">
                <thead class="bg-purple-800 h-auto">
                  <tr class='text-nowrap'>
                    <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-base font-semibold text-white sm:pl-6">Product Name</th>
                    <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-base font-semibold text-white sm:pl-6">Quantity Sold</th>
                    <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-base font-semibold text-white sm:pl-6">Total Sale</th>
                    <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-base font-semibold text-white sm:pl-6">Date of Sale</th>
                  </tr>
                </thead>
                <%= turbo_frame_tag "sales" do %>
                  <tbody class="divide-y divide-gray-300 bg-white">
                    <%= render @sales %>
                  </tbody>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      </div>
    <% end%>
  <% else %>
    <div class="max-w-lg mx-auto mt-8">
      <%= link_to new_admin_sale_path, data: { turbo_frame: "slide-over, #{dom_id(Sale.new)}" }, class: "relative block w-full border-2 border-gray-300 border-dashed rounded-lg p-12 text-center hover:border-gray-400 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500" do %>
        <svg class="mx-auto h-12 w-12 text-gray-400" xmlns="http://www.w3.org/2000/svg" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 14v20c0 4.418 7.163 8 16 8 1.381 0 2.721-.087 4-.252M8 14c0 4.418 7.163 8 16 8s16-3.582 16-8M8 14c0-4.418 7.163-8 16-8s16 3.582 16 8m0 0v14m0-4c0 4.418-7.163 8-16 8S8 28.418 8 24m32 10v6m0 0v6m0-6h6m-6 0h-6" />
        </svg>
        <span class="mt-2 block text-sm font-medium text-gray-900">Create New Sale</span>
      <% end %>
    </div>
  <% end %>
</div>

app/views/admin/sales/new.html.erb
<%= turbo_frame_tag @sale do %>
  <%= slide_over_form_wrapper(title: 'New Sale', subtitle: 'Make A New Sale') do %>
    <%= render 'form', sale: @sale %>
  <% end %>
<% end %>